name: Robot Framework

on:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: execute tests
        run: robot -v ENV:production -v OS:ANDROID -v DEVICE:NEXUS_5_ANDROID_12 --outputdir /Users/vuongvietvan/actions-runner/_work/bfxqa-robotframework/bfxqa-robotframework/reports /Users/vuongvietvan/Documents/GitHub/bfxqa-robotframework/e2e-tests/testcases/bitfinex/smoke/guest_user_test.robot
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: reports
  generate_report:
    if: always()
    needs: [test]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: reports
      - name: Send report to commit
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
