name: 'BrowserStack Test'
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: execute tests
        run: robot -v ENV:browserstack -v OS:ANDROID -v DEVICE:REALME_M2101K7AI --outputdir /reports e2e-tests/testcases/bitfinex/smoke/guest_user_test.robot
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: reports
  generate_report:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download reports
        uses: actions/download-artifact@v1
        with:
          name: reports
      - name: Send report to commit
        uses: saur-bh/bs@v2.1
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
